[package]
name = "projman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dialoguer = "0.12.0"
serde = { version = "1.0.227", features = ["derive"] }
serde_yaml = "0.9.34"
